### ISSUE TITLE
cf push reports : Stager error: Kpack build failed

### ISSUE THREAD

**Issue by cmoulliard** [cloudfoundry/cf-for-k8s#108]
## Issue

When we execute a push `cf push --hostname spring-music`, then pod created by kpack to build the container image fails and cf reports this message within the terminal

```
Error staging application: Stager error: Kpack build failed
FAILED
HTTP ERROR: [2020-04-01T08:56:22+02:00]
Get https://log-cache.95.217.161.67.nip.io/api/v1/info: context canceled
```

When I check the log of the pod created, the `prepare` step reports the following error
```
kc logs -n cf-workloads-staging pod/1e51074a-d26f-4a4c-80b9-0b4fdbfee826-build-1-wgffw-build-pod -c prepare
prepare:main.go:66: invalid credentials to build to /1e51074a-d26f-4a4c-80b9-0b4fdbfee826
```

## Additional information

- K8s cluster: `v1.16.7`
- cf: `6.50.0+4f0c3a2ce.2020-03-03`
- capi-api-server: `image: cloudfoundry/cloud-controller-ng:33f461df533c7174241b00759bb7622ea37c58c7@sha256:0bc1b2b3e0c2fcfbd76d7c4a311b728a240b928fcd8d2b2b1e057de88a0adacf`
- K8s resources created by kpack
```
kc get images,builds,builders,secrets -n cf-workloads-staging
NAME                                                          LATESTIMAGE   READY
image.build.pivotal.io/1e51074a-d26f-4a4c-80b9-0b4fdbfee826                 False
image.build.pivotal.io/e201f2fa-6149-4d4e-acea-3102de37ccd3                 False

NAME                                                                        IMAGE   SUCCEEDED
build.build.pivotal.io/1e51074a-d26f-4a4c-80b9-0b4fdbfee826-build-1-wgffw           False
build.build.pivotal.io/e201f2fa-6149-4d4e-acea-3102de37ccd3-build-1-6cwss           False

NAME                                             AGE
builder.build.pivotal.io/cf-autodetect-builder   10h

NAME                                                   TYPE                                  DATA   AGE
secret/cc-kpack-registry-auth-secret                   kubernetes.io/basic-auth              2      10h
secret/cc-kpack-registry-service-account-token-h8qls   kubernetes.io/service-account-token   3      10h
secret/default-token-6b567                             kubernetes.io/service-account-token   3      10h
secret/istio.cc-kpack-registry-service-account         istio.io/key-and-cert                 3      10h
secret/istio.default                                   istio.io/key-and-cert                 3      10h
```

## Investigation

I suspect that the error comes from the fact that kpack cannot access a container registry as the secret created by default contains empty values for docker

```
kc get -n cf-workloads-staging secret/cc-kpack-registry-auth-secret -o yaml
apiVersion: v1
data:
  password: ""
  username: ""
kind: Secret
metadata:
  annotations:
    build.pivotal.io/docker: ""
    kapp.k14s.io/identity: v1;cf-workloads-staging//Secret/cc-kpack-registry-auth-secret;v1
```

Questions:
- How can we configure the different container registries (address, username, pwd) ?
- Can we use a local container registry ?

**Comment by ericpromislow** [comment]
Hi @cmoulliard 

What happens if you change the `app_registry` block in your values file to something like this, redeploy and repush the app?

```
app_registry:
  hostname: hub.docker.com # or a private docker registry
  repository: REPOSITORY_NAME
  username: DOCKER_USER_NAME
  password: DOCKER_USER_PASSWORD
```

- Eric and @Birdrock
