### ISSUE TITLE
UAA client password is passed as a plain text to `cf-api-kpack-watcher`

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#225]
### Summary
The uaa client password is passed as a plain text to [`cf-api-kpack-watcher`](https://github.com/cloudfoundry/cf-for-k8s/blob/1772be2a06902d1f59a21037473f24bfd334853e/config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/capi-kpack-watcher-deployment.yml#L31) deployment config.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-api-kpack-watcher
...
    spec:
          ...
          - name: UAA_CLIENT_SECRET
           #@ data.values.uaa.clients.capi_kpack_watcher.secret
            value:  767rsvdi9dibu1us8voc  
``` 

### Expected behavior
It should use the k8s secret mechanism to consume the password. As per Kubernetes [docs](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets), the options are to either [mount them as files](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod) or consume them as [environment variables](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables).
