### ISSUE TITLE
The CC database password is passed as a plain text value to cloud-controller-ng-yaml config

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#226]
### Summary

The CC database password is passed as a plain text value to the Cloud Controller config map [`cloud-controller-ng-yaml` ](https://github.com/cloudfoundry/cf-for-k8s/blob/4eb5ad6fbcd149a1f8f5e1e8ad90c7bde4450be7/config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml#L115) 

```yaml
    ...
    db:
      database:
        adapter: postgres
        host: ...
        port: ...
        user: cloud_controller
        # password in configmap
        password: qeaxbngez299cr99qjvw
        database: cloud_controller
```
### Expected behavior
CAPI should use the k8s secret mechanism to consume the password. As per Kubernetes [docs](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets), the options are to either [mount them as files](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod) or consume them as [environment variables](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables).
