### ISSUE TITLE
CAPI UAA client secret is stored as a plain text in value in cloud-controller-ng-yaml configmap

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#228]
### Summary

The capi uaa client secret is stored as a plain text in capi config map https://github.com/cloudfoundry/cf-for-k8s/blob/4eb5ad6fbcd149a1f8f5e1e8ad90c7bde4450be7/config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml#L275

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-controller-ng-yaml
  namespace: cf-system
data:
  cloud_controller_ng.yml: |
    ...
    cloud_controller_username_lookup_client_name: cloud_controller_username_lookup
    cloud_controller_username_lookup_client_secret: 767rsvdi9dibu1us8voc
    ...
```
### Expected behavior
CAPI should use the k8s secret mechanism to consume the uaa client secret key. As per Kubernetes [docs](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets), the options are to either [mount them as files](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod) or consume them as [environment variables](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables).
