### ISSUE TITLE
UAA encryption passphrase is stored as a plain text value in uaa config map

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#229]
### Summary

The uaa encryption passphrase is stored as a plain text in UAA config map `uaa-config` 
https://github.com/cloudfoundry/cf-for-k8s/blob/f77fb368e6005a550a91ef74839de5aecdcbed4c/config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/uaa.lib.yml#L12

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: uaa-config
  namespace: cf-system
...
data:
  uaa.yml: |
    ....
      encryption_keys:
      - label: default_encryption_key
        passphrase: 864fyh6dl97q9b5ozo9g
    ...
```

### Expected behavior
UAA should use the k8s secret mechanism to store the encryption passphrase. As per Kubernetes [docs](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets), the options are to either [mount them as files](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod) or consume them as [environment variables](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables).
