### ISSUE TITLE
CF API Admin password is stored as a plain text in uaa config map

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#232]
### Summary
The CF API admin password is stored as a plain text in uaa config map
https://github.com/cloudfoundry/cf-for-k8s/blob/d6aa03c33987c1e1c036cb703700c6be5b3f2e41/config/uaa.yml#L58

```yaml
    scim:
      userids_enabled: true
      user:
        override: true
      users: # password embedded in the text
      - admin|1t5g5obe250y0mfdja8a|admin@admin.tld|first|last|clients.read,cloud_controller.admin,doppler.firehose,network.admin,openid,routing.router_groups.read,routing.router_groups.write,scim.read,scim.write|uaa
```
### Expected behavior
UAA should use the k8s secret mechanism to store the cf api admin password. As per Kubernetes [docs](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets), the options are to either [mount them as files](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod) or consume them as [environment variables](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables).
