### ISSUE TITLE
Apps fail to re-push after upgrading cf-for-k8s 

### ISSUE THREAD

**Issue by paulcwarren** [cloudfoundry/cf-for-k8s#257]
## Describe the bug
Apps fail to re-push after upgrading to cf-for-k8s/master at [this commit](https://github.com/cloudfoundry/cf-for-k8s/commit/14e0bf140aab34874bbbda4a4cc21f70cbc34b78). 

Our pipeline recently bumped cf-for-k8s to [this commit](https://github.com/cloudfoundry/capi-k8s-release/commits/a57882ad77cf480bc7c7d5d9cc99eb347f34bda2) of capi-k8s-release that included [this change](https://github.com/cloudfoundry/capi-k8s-release/commit/9cb980de9a0bc87ed80379fba7c26668578c8ef6) to remove the cf-autodetect-builder. 

The platform will attempt to re-push apps with this old builder and will therefore fail. 

## To Reproduce*
1. Deploy cf-for-k8s v0.3.0
2. Push an application
3. Upgrade to cf-for-k8s/14e0bf140aab34874bbbda4a4cc21f70cbc34b78
4. Re-push the application.

## Expected behavior
Application pushes successfully 

## Actual behavior
Application fails to push with the cf cli hanging right before staging starts and eventually timing out.

## Additional context
If you have access to the k8s cluster then running this command:

`$ k get image -n cf-workloads-staging <app_guid> -o yaml`

And inspecting the output for something like this:

``` 
 conditions:
  - lastTransitionTime: "2020-06-25T21:49:32Z"
    message: Unable to find builder cf-autodetect-builder.
    reason: BuilderNotFound
    status: "False"
    type: Ready
``` 

will confirm the issue.

### cf-for-k8s SHA 
14e0bf140aab34874bbbda4a4cc21f70cbc34b78

## Workarounds
Deleting the application, if possible, and re-pushing will resolve the situation.
