### ISSUE TITLE
Sharing small example of managing cf certificates with cert-manager

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry/cf-for-k8s#318]
**Is your feature request related to a problem? Please describe.**
I just wanted to demonstrate using cert-manager to provision let's-encrypt certs in the istio-system namespace for use with the istio gateway, instead of having to pass the `system_certificate` in as values 

**Describe the solution you'd like**
Be able to declare the certificate you'd like rather than generating it outside the cluster with `certbot` (or something else) and passing it in as a value

**Additional context**
Was inspired by this [quarks-secret](https://github.com/cloudfoundry/cf-for-k8s/pull/311) and the [google docs proposals on secrets](https://docs.google.com/document/d/1VKMVaBcIUjro_y38KwMskvqoqSXljqVcLA_CVPTHbXU/edit) and [secretgen-controller and such](https://github.com/k14s/secretgen-controller)

I slapped this together [in an example in this PR over here](https://github.com/aegershman/deployments/pull/174) using a ytt overlay to remove the creation of the `secret` and replace it with a `cert-manager` `certificate` resource request. Here's what it looks like:

```yml
# cert-manager cert issuer, assuming this already exists on the cluster with cert-manager:
---
apiVersion: cert-manager.io/v1beta1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: youremail+letsencrypt@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          route53:
            region: us-east-2
```

and then the ytt config-optional overlay that'd be used with `cf`

```yml
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Secret","metadata":{"name":"cf-system-cert"}})
#@overlay/remove
---
---
apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: cf-system-prod
  namespace: istio-system
  annotations:
    kapp.k14s.io/change-rule.istio-ingressgateway: "upsert before upserting istio.io/ingressgateway"
spec:
  secretName: cf-system-cert
  dnsNames:
    - "*.cf.yourcloudfoundryaddress.biz"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Never
```

this will have cert-manager leverage letsencrypt to create the `cf-system-cert` secret instead of having it be passed in as a data value [as described here in the doc](https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/platform_operators/setup-ingress-certs-with-letsencrypt.md) for generating a letsencrypt cert using certbot

the power of this is that you don't have to worry about your credentials for the certificate being stored in a credential manager or anything; you just declare that you want a certificate, and it's taken care of for you (eventually) within the cluster

feel free to close this out whenever, I just wanted to share this as an issue in case other folks were interested or came across it. it's not perfect, I just wanted to share as an example 👍 

thanks all
