### ISSUE TITLE
Identity for Apps Proposal (the feature formally known as Route Intregrity)

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-for-k8s#368]
## Background

Cloud Foundry for VMs [uses TLS certificates to prevent misrouting](https://docs.cloudfoundry.org/concepts/http-routing.html#consistency) -- a feature we colloquially refer to as Route Integrity. This protects against the case where the Ingress Gateway’s internal routing table is out of date by first validating the destination’s identity. If there is a certificate mismatch the request will fail and traffic will not be delivered to the wrong destination.

Istio can do this as part of mesh mutual TLS (mTLS), but only if each app has a unique certificate. Istio [uses the service account that is assigned to a Pod](https://istio.io/latest/blog/2017/0.1-auth/#strong-identity) to identify a workload and uses this to determine the SAN on the workload's X.509 certificate that it uses for mTLS. So, in short, we need to have a distinct service account per Cloud Foundry app.

## Proposal
**We will write a mutating webhook that will bind app-unique service accounts for each app statefulset and a controller that owns the creation of the service accounts/associated resources.** This design draws inspiration from the Knative Binding pattern (viewing requires joining the knative-users mailing list). More specifically, this includes building two parts: a mutating admission webhook and a ServiceAccount/RoleBinding reconciling controller (we need to bind to the [existing Eirini workload role](https://github.com/cloudfoundry-incubator/eirini-release/blob/075ad3d13528515af165df257ba7dc67a81de40e/deploy/workloads/workloads-rbac.yml#L9) and potentially others in the future).

The webhook will be responsible for altering the StatefulSets to inject our new per-app service account. The controller will be responsible for reconciling the new per-app service accounts injected by the web hook, as well as binding the appropriate roles to the new service account.

The webhook and controller will be configured via a ConfigMap. It will define what “Pod Spec”-able (things with a template that declares a `pod.spec`) resources our webhook will mutate. It will also give the controller the information it needs to know which “PodSpec”-able resources to watch for so that it can create the necessary ServiceAccounts. Additionally we declare what (Cluster)RoleBindings should be created for the new ServiceAccounts.

#### Scaling Concerns
In terms of scaling this solution, there is a risk of write amplification on etcd. Creating a new service account results in a number of second-order effects that put additional load on the platform -- things like JWT token creation/rotation. These increase the amount of data stored in etcd as well as the number of writes. We will have to deploy this with our scale tests to really find out whether it will cause problems at CF4K8s GA scale.

### Example ConfigMap
The configuration for our components will look something like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-account-controller-config
  namespace: cf-system
data:
  service-account-controller.yaml:
    selectors:
    - matchLabels:
        cloudfoundry.org/source_type: APP
      namespace: cf-workloads
    - matchLabels:
        cloudfoundry.org/source_type: TASK
      namespace: cf-workloads
    - matchLabels:
        # Staging tasks are not actually pod-specable
        # kpack does not give control of the pod template
        # If we want to support identity for staging tasks we may have to mutate the pod and investigate how this affects kpack
        cloudfoundry.org/source_type: STG
        namespace: cf-workloads-staging
    roles:
    # https://github.com/cloudfoundry-incubator/eirini-release/blob/master/deploy/workloads/workloads-rbac.yml
    - "eirini-workloads-app-role"
    - "foo-role"
    cluster_roles:
    - "bar-role"
```

## Describe alternatives you've considered
The majority of this exploration was completed as part of [#170777302](https://www.pivotaltracker.com/story/show/170777302). You can read our [Google doc](https://docs.google.com/document/d/182wjnQRyjIc7oBffvaeP37JlivAXMmZQT3kTK5bZWYE/edit?ts=5f3213cc#) to see the discussion and some of the alternatives we considered.

## Additional context
* [Identity in Istio](https://istio.io/latest/blog/2017/0.1-auth/#strong-identity)
* [Cloud Foundry Instance Identity](https://docs.cloudfoundry.org/devguide/deploy-apps/instance-identity.html)
