### ISSUE TITLE
App Developers can expect their apps with Procfile + app language will be correctly detected

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#408]
**Is your feature request related to a problem? Please describe.**
Slack thread => https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1598642490103900
Problem: A language app like Python can have `Procfile` in its root folder. However, `Procfile` buildpack is ignored in favor of the app language buildpack. In this scenario, we need both the language buildpack and the `Procfile` buildpack to detect and participate in building the app image

**Describe the solution you'd like**
As per buildpacks team, add `Procfile` as an optional buildpack to all languages

**Given** that I have cf-for-k8s custombuilder config [here](https://github.com/cloudfoundry/cf-for-k8s/blob/master/config/kpack/default-buildpacks.yml#L32)
**When** I look at the buildpacks grouping in the custombuilder
**Then** I expect `Procfile` buildpack declaration (see below snipped) in every group **except** the `Procfile` group which should be the last group
```
group: 
     - id: <current buildpack>
     - id: paketo-buildpacks/procfile
       optional: true
group:
     - id: <current buildpack>
     - id: paketo-buildpacks/procfile
        optional: true
```
---
**Given** that I have cf-for-k8s custombuilder with the above order
**When** I install cf-for-k8s on a cluster
**Then** I can cf-push the following apps individually that may also have `Procfile` and without using `-b` option
- ruby, node, go, python, php, nginx, java, dotnet-core, procfile, staticfile

### Notes
- For the second acceptance criteria, we could see if CATS (some assets in CATS have Procfile) in cf-for-k8s can run those languages. If not, we may have to figure out how we might test the order correctly.
