### ISSUE TITLE
Need the ability to add annotations to the LoadBalancer Service

### ISSUE THREAD

**Issue by amalagaura** [cloudfoundry/cf-for-k8s#537]
**Is your feature request related to a problem? Please describe.**
We have a private IP network in AWS and when creating the load balancer from the Service with type LoadBalancer it requires some extra annotations.

**Describe the solution you'd like**
Section in the cf-values.yaml in which we can add annotations to the Istio Load Balancer service

**Describe alternatives you've considered**

**Additional context**

**Comment by aegershman** [comment]
in a pinch you could include a [`ytt` overlay](https://github.com/k14s/ytt/blob/develop/docs/lang-ref-ytt-overlay.md). as an example a file named `nlb-overlay.yml` (or something), like so:

```yml
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Service","metadata":{"name":"istio-ingressgateway"}})
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    #@overlay/match missing_ok=True
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```

and if we use the example snippet from [step 5 of the intro `deploy` doc here](https://github.com/cloudfoundry/cf-for-k8s/blob/develop/docs/deploy.md), we'd pop in our overlay file like so:

```sh
ytt -f config -f nlb-overlay.yml -f ${TMP_DIR}/cf-values.yml > ${TMP_DIR}/cf-for-k8s-rendered.yml
```

another option would be if you were set on having the annotations be in a values file instead of the overlay itself, you could take parts of this [ytt overlay example](https://get-ytt.io/#example:example-k8s-helm-ish) (I haven't tested this myself):

```yml
#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Service","metadata":{"name":"istio-ingressgateway"}})
---
metadata:
  #@ if/end data.values.ingress.annotations:
  #@overlay/match missing_ok=True
  annotations: #@ data.values.istio_ingressgateway.additional_annotations
```

and in `values.yml`, you could include:

```yml
...
istio_ingressgateway:
  additional_annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```

🤷‍♀️ I won't clutter your issue thread, I'll let others respond with other guidance. I'm just puttin' out ideas; that's just what's worked for me pretty well with using `ytt` to suit my deployment topology needs 👍
