### ISSUE TITLE
Manifest annotations and labels should be applied to cf-workload pods

### ISSUE THREAD

**Issue by braunsonm** [cloudfoundry/cf-for-k8s#579]
## Describe the bug
CF Manifests support annotations and labels. These should be translated to labels and annotations on the pods to allow greater customization.

For instance in our usecase we want to apply a certain policy using a podSelector. If we could deploy our apps with a label using the manifest, we could match on that label.

## To Reproduce*
1. Create a test app with this manifest:
```
---
applications:
  - name: go-webserver
    health-check-type: process
    instances: 1
    metadata:
      annotations:
        another: "hey"
      labels:
        test: "hello"
```
2. cf push
3. Notice that neither the annotation nor metadata gets applied on the pod

**Comment by Birdrock** [comment]
@piyalibanerjee @matt-royal What do y'all think of this request?

**Comment by braunsonm** [comment]
For a use-case, since cf-for-k8s doesn't support internal domains or C2C communication, we were going to have apps tag themselves as internal with a label. Then disable ingress access using a network policy matching that label.

```yaml
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-app-ingress-internal-services
  namespace: cf-workloads
spec:
  podSelector:
    matchLabels:
      mydomain/internal: true
  policyTypes:
  - Ingress
```

This coupled with a Sidecar rule to allow C2C is currently the **only** way for CF apps to talk to eachother without going through the internet. We have some apps which do not have authentication on them and are meant for internal usage only.
