### ISSUE TITLE
cf-push buildpack apps does not work with dockerhub.com registry

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#71]
## Expected Behavior
I expect cf-push build pack to work with dockerhub.com registry, since it is a publicly trusted registry.

## Actual Behavior
cf-push fails when using dockerhub.com as a cf-app registry

## Steps to Reproduce the Problem

  1. Add the following to `cf-install-values.yaml`
```
kpack:
  registry:
    hostname: https://index.docker.io/v1/
    repository: <my repository url>
    username: <my username>
    password: <my password>
```
  1. Go through instructions to install cf-4-k8s and configure cf-cli to connect to the foundation
  1. `cf push spring-petclinic -p /Users/saikiranyerram/workspace/spring-petclinic`
  1. Notice the failure

## Specifications

  - Version: cf-for-k8s / latest
  - Platform: GKE v1.13.12-gke.25
  - Subsystem:

**Comment by zankich** [comment]
I tried to use dockerhub and also experienced a failure.

I looked at the kpack logs and saw this
```
$ kubectl -n kpack logs deployment.apps/kpack-webhook
...
"error": "invalid value: https://index.docker.io/v1/<repository>/f2fb9409-1b4e-477f-9df2-e0fbb36d4e72: spec.tag"
...
```

For dockerhub tag capi is injecting the incorrect value for the kpack `tag`. The value should not include `https://index.docker.io/v1/`.

https://github.com/cloudfoundry/cf-for-k8s/blob/bd7b4f6efba37e5eb418430cd270b06fcf8725fd/config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml#L366

If you remove the interpolation of `data.values.kpack.registry.hostname` then it works.

My `cf-values.yml` has the following kpack settings
```
kpack:
  registry:
    hostname: https://index.docker.io/v1/
    repository: <username>
    username: <username>
    password: <password>
```

The kpack [docs](https://github.com/pivotal/kpack/blob/master/docs/tutorial.md) mention
```
Make sure to replace <DOCKER-IMAGE> with the registry you configured in step #2. Something like: your-name/app or gcr.io/your-project/app
```

So that explains why the interpolation values work for gcr but not dockerhub.

**Comment by selzoc** [comment]
I think we also use the `kpack.registry.hostname` for the [registry auth secret](https://github.com/cloudfoundry/capi-k8s-release/blob/master/templates/service-accounts.yml#L30) - maybe that's an indication that we should stop conflating the two concepts.

Would it make sense to have a separate value that was just the "destination repository" for app images?  Then in the dockerhub case:
```yaml
kpack:
  registry:
    hostname: https://index.docker.io/v1/
    repository: cloudfoundry/capi
    username: <username>
    password: <password>
```

and the gcr case:
```yaml
kpack:
  registry:
    hostname: gcr.io
    repository: gcr.io/your-project/capi
    username: <username>
    password: <password>
```

even though it's a bit redundant.
