### ISSUE TITLE
cf-push -o image_internal_docker_registry and backoff pulling due to DNS resolution issue

### ISSUE THREAD

**Issue by cmoulliard** [cloudfoundry/cf-for-k8s#73]
## Issue

An image pushed to the internal docker registry of `cf-for-k8s` cannot be pulled by the pod created by `cf push -o docker-registry.docker-registry.svc.cluster.local:5000/sb/demo`.
The pod reports the error `Back-off pulling image "docker-registry.docker-registry.svc.cluster.local:5000/sb/demo@sha256:cfeb34a5055048821c0a4fc0e199ee202f02c51f13eacefaed2591462cf40c91"`

## How to reproduce

- Install kpack and buildpacks
```
mkdir kpack && cd kpack/
wget https://github.com/pivotal/kpack/releases/download/v0.0.6/release-0.0.6.yaml
kc apply -f release-0.0.6.yaml

cat << _EOF_  > cluster-builder.yml
apiVersion: build.pivotal.io/v1alpha1
kind: ClusterBuilder
metadata:
  name: default
spec:
  image: cloudfoundry/cnb:0.0.55-bionic
_EOF_   
kc apply -f cluster-builder.yml
```
- Create an image k8s resource to build the `spring-petclinic` project from git
```
cat << _EOF_  > image.yml
apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: tutorial-image
spec:
  tag: docker-registry.docker-registry.svc.cluster.local:5000/sb/demo
  serviceAccount: tutorial-service-account
  cacheSize: "1.5Gi"
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/spring-projects/spring-petclinic
      revision: 82cb521d636b282340378d80a6307a08e3d4a4c4
_EOF_
kc apply -f image.yml -n kpack
```
- Check the status of the build/image
```
kc get images -n kpack
NAME                                    LATESTIMAGE                                                                                                                              READY
image.build.pivotal.io/tutorial-image   docker-registry.docker-registry.svc.cluster.local:5000/sb/demo@sha256:cfeb34a5055048821c0a4fc0e199ee202f02c51f13eacefaed2591462cf40c91   True
```
- Create an application using `cf push`
```
cf push sb-demo -o docker-registry.docker-registry.svc.cluster.local:5000/sb/demo@sha256:cfeb34a5055048821c0a4fc0e199ee202f02c51f13eacefaed2591462cf40c91
```
- Check the status of the pod created
```
kc get pods -n cf-workloads
NAME                                 READY   STATUS             RESTARTS   AGE
sb-demo-demo-cefdcee0ca-0            1/2     ImagePullBackOff   0          9h      

Back-off pulling image "docker-registry.docker-registry.svc.cluster.local:5000/sb/demo@sha256:cfeb34a5055048821c0a4fc0e199ee202f02c51f13eacefaed2591462cf40c91"
```

### Pod info

https://gist.github.com/cmoulliard/a883cc13087c12d7ee986220806cf5f2

### Investigations

1) DNS Issue

I think that the problem is related to a DNS resolution issue as reported by this warning
```
 Warning  Failed     3m16s (x3 over 4m)     kubelet, cf-k8s-control-plane  Failed to pull image "docker-registry.docker-registry.svc.cluster.local:5000/sb/demo@sha256:cfeb34a5055048821c0a4fc0e199ee202f02c51f13eacefaed2591462cf40c91": 
rpc error: code = Unknown desc = failed to pull and unpack image "docker-registry.docker-registry.svc.cluster.local:5000/sb/demo@sha256:cfeb34a5055048821c0a4fc0e199ee202f02c51f13eacefaed2591462cf40c91":
failed to resolve reference "docker-registry.docker-registry.svc.cluster.local:5000/sb/demo@sha256:cfeb34a5055048821c0a4fc0e199ee202f02c51f13eacefaed2591462cf40c91":
failed to do request: Head https://docker-registry.docker-registry.svc.cluster.local:5000/v2/sb/demo/manifests/sha256:cfeb34a5055048821c0a4fc0e199ee202f02c51f13eacefaed2591462cf40c91:
dial tcp: lookup docker-registry.docker-registry.svc.cluster.local: no such host
```
2) ImagePullSecret and credential

If I check the configuration of the `statefulset` k8s resource of the sb-demo pod, it includes an 
```
      imagePullSecrets:
      - name: registry-credentials
```
but no `registry-credentials` secret exists with the docker registry credential
```
kc get secrets -n cf-workloads
NAME                            TYPE                                  DATA   AGE
default-token-ss85w             kubernetes.io/service-account-token   3      38h
eirini-privileged-token-hhq5b   kubernetes.io/service-account-token   3      38h
eirini-token-tpv75              kubernetes.io/service-account-token   3      38h
istio.default                   istio.io/key-and-cert                 3      38h
istio.eirini                    istio.io/key-and-cert                 3      38h
istio.eirini-privileged         istio.io/key-and-cert                 3      38h
```

Should a secret with credentials created to access the docker registry ?
